import Link from "next/link";
import { LinkButton } from "@/components/ui/Button";

const steps = [
  {
    n: "01",
    title: "Housing type & floor plan",
    body: "Consumer picks their housing type and uploads a floor plan. AI segments it into rooms automatically.",
  },
  {
    n: "02",
    title: "Inspiration & theme",
    body: "Inspo images go in per room, plus an overall colour scheme and style theme.",
  },
  {
    n: "03",
    title: "Room requirements",
    body: "A required prompt per room captures must-haves — oven, wardrobe, whatever the room needs.",
  },
  {
    n: "04",
    title: "AI suggestions",
    body: "AI generates room concepts and an updated 2D floor plan — a shared brief the designer can start from.",
  },
];

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="mx-auto w-full max-w-5xl px-6 py-6 flex items-center justify-between">
        <span className="font-display text-xl font-semibold tracking-tight">Roomly</span>
        <span className="text-xs uppercase tracking-widest text-stone-400">
          AWS Show Me Ur Agents
        </span>
      </header>

      <section className="mx-auto w-full max-w-5xl px-6 pt-10 pb-16">
        <p className="text-xs uppercase tracking-widest text-amber-700 font-medium mb-4">
          Design inspiration, aligned
        </p>
        <h1 className="font-display text-4xl sm:text-5xl leading-[1.1] font-medium max-w-2xl">
          Close the gap between what consumers picture and what designers hear.
        </h1>
        <p className="mt-5 max-w-xl text-stone-600 text-base sm:text-lg">
          Roomly turns a floor plan, a Pinterest board, and a few must-haves into one
          structured design brief — room-by-room AI suggestions and a 2D layout —
          before the designer ever picks up a pencil.
        </p>
        <div className="mt-8 flex items-center gap-4">
          <LinkButton href="/project/housing">Start a new project</LinkButton>
          <Link href="#how" className="text-sm text-stone-500 hover:text-stone-900">
            See how it works
          </Link>
        </div>
      </section>

      <section id="how" className="border-t border-stone-200 bg-white">
        <div className="mx-auto w-full max-w-5xl px-6 py-16">
          <h2 className="font-display text-2xl font-medium mb-10">How it works</h2>
          <div className="grid sm:grid-cols-2 gap-x-10 gap-y-10">
            {steps.map((s) => (
              <div key={s.n} className="flex gap-4">
                <span className="font-display text-3xl text-stone-300">{s.n}</span>
                <div>
                  <h3 className="font-medium text-stone-900">{s.title}</h3>
                  <p className="mt-1 text-sm text-stone-600">{s.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="mx-auto w-full max-w-5xl px-6 py-16">
        <div className="rounded-2xl border border-stone-200 bg-stone-100/60 p-8 sm:p-10">
          <h2 className="font-display text-xl font-medium mb-2">Powered by Amazon Bedrock</h2>
          <p className="text-sm text-stone-600 max-w-2xl">
            Room segmentation and design-brief reasoning run on Claude Sonnet 4.5 via
            Bedrock. Room-concept images are generated by a Bedrock image model
            (e.g. Titan Image Generator / Nova Canvas), prompted from Sonnet&nbsp;4.5&apos;s
            room brief. This demo runs against a mocked AI layer with the same
            interface, so swapping in the real Bedrock calls is a drop-in change.
          </p>
        </div>
      </section>

      <footer className="mt-auto border-t border-stone-200">
        <div className="mx-auto w-full max-w-5xl px-6 py-8 text-xs text-stone-400 flex items-center justify-between">
          <span>Roomly — hackathon prototype</span>
          <LinkButton href="/project/housing" variant="ghost" size="sm">
            Start a project →
          </LinkButton>
        </div>
      </footer>
    </div>
  );
}
